#!/usr/bin/env python3
"""2f - the Caddyfile, generated, and REFUSING without PUBLIC_HOSTNAME.

    PUBLIC_HOSTNAME=webhooks.example.com py -3 scripts/server/generate_caddyfile.py
    py -3 scripts/server/generate_caddyfile.py --out build/Caddyfile

PUBLIC_HOSTNAME IS A NAMED, UNFILLED OPERATOR INPUT AND THIS REFUSES RATHER
THAN GUESSING ONE. Per the operator's instruction for 2e and 2f. A guessed
hostname is not a harmless placeholder here: Caddy would attempt an ACME
issuance against it on startup, which is a real request to a real certificate
authority for a name we do not control. Getting that wrong is rate-limited by
Let's Encrypt for a week, and the rate limit applies to the ACCOUNT.

TLS-ALPN, NOT HTTP-01, AND THE FIREWALL IS THE REASON. `provision.sh` step 1
opens 22 and 443 and nothing else - default deny. HTTP-01 validation requires
port 80, so it would fail, and the failure arrives as a certificate that
never issues rather than as anything naming the firewall. TLS-ALPN-01 runs
entirely over 443, which is the port that is actually open.

It is selected by DISABLING the HTTP challenge, not by naming ALPN:
`alpn` is a valid `tls` subdirective that sets the server's protocol
list and has nothing to do with ACME. Writing it there validated
cleanly and changed nothing, and Caddy tried HTTP-01 on a closed port.

    tls { issuer acme { disable_http_challenge } }

Opening 80 to use HTTP-01 instead would be the other way to fix it, and it
is the wrong one: it widens the firewall to satisfy a validation method we
did not need.

WHAT IS PROXIED, AND WHAT IS NOT. Exactly one path reaches exactly one
loopback port: the record-only webhook receiver. The web application is NOT
exposed. Nothing else on the host is reachable from the internet, and the
default route is a refusal rather than a 404 that invites a scan.
"""
import argparse
import io
import os
import re
import sys

PUBLIC_HOSTNAME = "PUBLIC_HOSTNAME"

#: Where the receiver listens. Loopback: Caddy terminates TLS in front of it
#: and the receiver must never be reachable directly.
RECEIVER_PORT = 8787
WEBHOOK_PATH = "/webhook"

#: A hostname, not a URL and not an IP. Checked because a value like
#: `https://x.example.com/` in this field produces a Caddyfile that parses
#: and a site block that never matches.
_HOSTNAME = re.compile(
    r"^(?=.{1,253}$)(?!-)[A-Za-z0-9-]{1,63}(?<!-)"
    r"(\.(?!-)[A-Za-z0-9-]{1,63}(?<!-))+$")


def caddyfile(hostname, port=RECEIVER_PORT):
    return """\
# GENERATED by scripts/server/generate_caddyfile.py. Do not hand-edit.
#
# TLS-ALPN-01, not HTTP-01: provision.sh opens 22 and 443 only, default deny.
# HTTP-01 needs port 80 and would fail as a certificate that never issues,
# naming nothing about the firewall.

{
\t# A failed issuance should be loud in the log rather than retried quietly.
\tlog {
\t\tlevel INFO
\t}
}

%(hostname)s {
\ttls {
\t\t# `disable_http_challenge` IS THE DIRECTIVE THAT SELECTS THE CHALLENGE.
\t\t# An earlier version of this file wrote `alpn tls-alpn-01` here and was
\t\t# wrong in the most expensive way available: `alpn` IS a valid `tls`
\t\t# subdirective - it sets the server's ALPN protocol list - so
\t\t# `caddy validate` answered "Valid configuration", and Caddy went and
\t\t# tried HTTP-01 anyway. It failed against the closed port 80 with
\t\t# "Timeout during connect (likely firewall problem)" - which is exactly
\t\t# the failure the comment above claimed to be preventing.
\t\t#
\t\t# Valid syntax meaning something else entirely is worse than a syntax
\t\t# error, because the validator agrees with you.
\t\tissuer acme {
\t\t\tdisable_http_challenge
\t\t}
\t}

\t# EXACTLY ONE PATH IS PROXIED, and it is the record-only receiver. The
\t# web application is deliberately not exposed.
\thandle %(path)s* {
\t\treverse_proxy 127.0.0.1:%(port)d {
\t\t\t# The receiver drains an oversized body before refusing it, so
\t\t\t# the sender can read the answer. Give it room to do that: a
\t\t\t# proxy that gives up first re-creates the broken pipe one hop
\t\t\t# further out.
\t\t\ttransport http {
\t\t\t\tread_timeout 30s
\t\t\t\twrite_timeout 30s
\t\t\t}
\t\t}
\t}

\t# Anything else is refused rather than 404'd. A 404 confirms the host is
\t# serving and invites the next request; this says nothing useful.
\thandle {
\t\trespond "not in service" 403
\t}

\theader {
\t\tStrict-Transport-Security "max-age=31536000"
\t\tX-Content-Type-Options "nosniff"
\t\t-Server
\t}
}
""" % {"hostname": hostname, "path": WEBHOOK_PATH, "port": port}


def main():
    ap = argparse.ArgumentParser(description="Generate the Caddyfile")
    ap.add_argument("--out")
    ap.add_argument("--hostname", help="overrides $%s" % PUBLIC_HOSTNAME)
    ap.add_argument("--port", type=int, default=RECEIVER_PORT)
    args = ap.parse_args()

    hostname = (args.hostname or os.environ.get(PUBLIC_HOSTNAME) or "").strip()
    if not hostname:
        sys.stderr.write(
            "REFUSING to generate a Caddyfile: %s is unset.\n\n"
            "  It is a named, unfilled operator input and there is no safe\n"
            "  default. A guessed hostname is not a placeholder: Caddy\n"
            "  attempts an ACME issuance for it at startup, which is a real\n"
            "  request to a real certificate authority for a name we do not\n"
            "  control. Let's Encrypt rate-limits failures for a week, and\n"
            "  the limit applies to the ACCOUNT.\n\n"
            "  Set it and re-run:  %s=webhooks.example.com\n"
            % (PUBLIC_HOSTNAME, PUBLIC_HOSTNAME))
        return 2

    # An IPv4 literal matches the hostname pattern above - digits and dots
    # are legal label characters - and ACME cannot issue a certificate for a
    # bare address at all. Caught by the test, not by reading the regex. The
    # rule that separates them is that a top-level label is never numeric.
    looks_like_ip = all(part.isdigit() for part in hostname.split(".") if part)
    if looks_like_ip or hostname.rsplit(".", 1)[-1].isdigit():
        sys.stderr.write(
            "REFUSING: %r is an IP address, not a hostname.\n\n"
            "  ACME cannot issue a certificate for a bare address, so Caddy\n"
            "  would start, try, and fail - and the failure counts against\n"
            "  the account's rate limit like any other.\n" % (hostname,))
        return 2

    if not _HOSTNAME.match(hostname):
        sys.stderr.write(
            "REFUSING: %r is not a hostname.\n\n"
            "  It must be a bare dotted name - not a URL, not an IP, no\n"
            "  scheme and no path. A URL here produces a Caddyfile that\n"
            "  parses and a site block that never matches, which looks like\n"
            "  a networking problem for as long as you let it.\n"
            % (hostname,))
        return 2

    text = caddyfile(hostname, args.port)
    if args.out:
        # newline="\n": a Caddyfile written from Windows with CRLF is defect
        # 4f's shape again.
        with io.open(args.out, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
        sys.stderr.write("wrote %s for %s\n" % (args.out, hostname))
        return 0
    sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
