#!/usr/bin/env python3
"""2h - the three tmux session units, generated, with enable-linger named.

    py -3 scripts/server/generate_tmux_units.py --check
    py -3 scripts/server/generate_tmux_units.py --out-dir build/systemd-user

USER services, not system ones, so the sessions belong to `resonate` and
carry its environment and its Claude Code credentials.

LINGERING IS THE PART THAT IS EASY TO MISS, and it is the only reason this
file prints an instruction as well as writing units. A user manager normally
starts at first login and stops at last logout, so a session enabled this way
would NOT come back after a reboot until somebody logged in - which is the
opposite of what these are for. The verification in
docs/SERVER-PACKAGE-2H-TMUX-SESSIONS.md §6 is explicit that you must check
BEFORE logging in, because logging in is exactly what hides a missing
`enable-linger`.

    sudo loginctl enable-linger resonate

THREE CONCRETE UNITS, NOT ONE TEMPLATE. `tmux-session@.service` with `%i`
would be tidier, but the working directory differs per session and `%h/%i`
does not spell any of the three real paths - `resonate-group-automation`,
`resonate-slack-agent`, `resonate-infra` are not a pattern over the session
names `production`, `agent`, `infra`. The spec says three concrete units are
simpler to read and this package prefers that.

Restart=no ON PURPOSE. A session killed by hand should STAY killed;
`Restart=always` would resurrect it under the operator and make
`tmux kill-session` look broken.
"""
import argparse
import io
import os
import sys

APP_USER = os.environ.get("APP_USER", "resonate")
APP_HOME = "/home/%s" % APP_USER

#: session name -> the worktree it opens in, relative to the app user's home.
#: From docs/SERVER-PACKAGE-2H-TMUX-SESSIONS.md §1.
SESSIONS = (
    ("production", "resonate-group-automation"),
    ("agent", "resonate-slack-agent"),
    ("infra", "resonate-infra"),
)

TMUX = "/usr/bin/tmux"


def unit(session, worktree, home=APP_HOME):
    return """\
# GENERATED by scripts/server/generate_tmux_units.py. Do not hand-edit.
[Unit]
Description=tmux session %(session)s for resonate
After=default.target

[Service]
# `new-session -d` returns immediately and the server keeps running after
# tmux exits, so Type=forking is correct and RemainAfterExit is not.
Type=forking
ExecStart=%(tmux)s new-session -d -s %(session)s -c %(dir)s
ExecStop=%(tmux)s kill-session -t %(session)s
# A session killed by hand should STAY killed. Restart=always would
# resurrect it under the operator and make `tmux kill-session` look broken.
Restart=no

[Install]
WantedBy=default.target
""" % {"session": session, "dir": "%s/%s" % (home, worktree), "tmux": TMUX}


def instructions(home=APP_HOME):
    names = " ".join("tmux-%s" % s for s, _ in SESSIONS)
    return """\
# Install, as the app user:
mkdir -p ~/.config/systemd/user
cp tmux-*.service ~/.config/systemd/user/
systemctl --user daemon-reload
systemctl --user enable --now %(names)s

# THE STEP THAT IS EASY TO MISS, and it needs root:
sudo loginctl enable-linger %(user)s

# Without it the user manager stops at last logout and NONE of these come
# back after a reboot until somebody logs in - which is the opposite of what
# they are for, and it fails exactly when it is needed: after an unattended
# 02:00 reboot, with nobody logged in.

# VERIFY AFTER A DELIBERATE REBOOT, AND DO NOT LOG IN FIRST:
#   1. sudo reboot
#   2. wait for ssh. Do NOT log in as a way of starting anything.
#   3. systemctl --user list-units 'tmux-*'     all three active
#   4. tmux ls                                  production, agent, infra
# Step 2 is the real test: if the sessions only appear once you have logged
# in, lingering is not enabled.
""" % {"names": names, "user": APP_USER}


def main():
    ap = argparse.ArgumentParser(description="Generate the three tmux user units")
    ap.add_argument("--out-dir")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--home", default=APP_HOME)
    args = ap.parse_args()

    units = {"tmux-%s.service" % s: unit(s, w, args.home) for s, w in SESSIONS}

    if args.check or not args.out_dir:
        for name, text in sorted(units.items()):
            sys.stdout.write("# ---- %s\n%s\n" % (name, text))
        sys.stdout.write(instructions(args.home))
        sys.stderr.write("\n--check: nothing written. %d units.\n" % len(units))
        return 0

    os.makedirs(args.out_dir, exist_ok=True)
    for name, text in sorted(units.items()):
        path = os.path.join(args.out_dir, name)
        # newline="\n" explicitly: a unit written from Windows with CRLF is
        # defect 4f wearing a different hat.
        with io.open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
        sys.stderr.write("wrote %s\n" % path)
    path = os.path.join(args.out_dir, "INSTALL.sh")
    with io.open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(instructions(args.home))
    sys.stderr.write("wrote %s\n" % path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
