#!/usr/bin/env python3
""""You have not met them" was generated about people we had written to.

`claims.prior_contact` reads `rec["events"]` and nothing else. That is the right
authority for what it LICENSES - "as discussed" needs a touch we confirmed - but
it was also the only input to the draft prompt's shape, and across this estate
the provider confirms 912 sends against ONE recorded local touch in 1,582
records. So for all but one person the absence of a local event was read as
positive evidence of never having written, and `prompts/draft.md` asserted,
verbatim:

    "There is nothing to own and nothing to apologise for. You have not failed
     them; you have not met them."

A flat statement about a real person, generated by us, false for every STARI
LEAD and every manually-touched COLD lead. That sentence is now gone from the
prompt and the authority under the field is `claims.prior_contact_state`, which
rests on the same provider evidence `collision.classify` uses.

INVARIANT 0 IS WHAT THESE TESTS ARE ABOUT. One canonical authority per question,
and an unreadable authority means UNKNOWN - which never becomes PASS, zero,
idle, complete, safe, or "never contacted". There is no safe boolean here: a
`false` writes "we have not met" and a `true` writes "as discussed", and both
are false claims about somebody nobody has looked up. So the answer has three
values and the third one is the common case.

Every fixture is built through the real parsers from documented provider row
shapes, reusing `tests/test_a_lead_is_classified_before_it_is_contacted.py`'s
builders, so a dossier here cannot drift from one the provider would produce.
"""
import unittest

from src import claims, collision
from tests.base import QueueTest
from tests.test_a_lead_is_classified_before_it_is_contacted import (
    MANUAL, OS_CAMPAIGNS, OURS, cold_baseline, conversation, email_side,
    linkedin_side, membership, sent_row)

CONTACT = {"key": "dana", "email": "dana@kestrelwharf.test"}


def dossier(email=None, link=None):
    return collision.recontact_dossier(
        email=email if email is not None else cold_baseline(),
        linkedin_=link if link is not None else linkedin_side(rows=()))


def absent_everywhere():
    """The provider holds no lead row and our inbox holds no thread."""
    return collision.recontact_dossier(
        email=collision.email_history(lead_row=None,
                                      lookup=collision.LOOKUP_ABSENT,
                                      bindings={}, os_campaigns=OS_CAMPAIGNS,
                                      ledger_readable=True),
        linkedin_=linkedin_side(rows=()))


def record(events=()):
    return {"id": "kestrelwharf-test", "events": list(events)}


class AnEmptyLocalLedgerProvesNothing(QueueTest):

    def test_no_provider_evidence_at_all_is_unknown(self):
        """THE DEFECT, DIRECTLY. The old code returned a proven negative here."""
        self.assertEqual(claims.PRIOR_CONTACT_UNKNOWN,
                         claims.prior_contact_state(record(), CONTACT))
        self.assertFalse(claims.may_claim_first_contact(record(), CONTACT),
                         "an empty local log may NEVER license 'we have not "
                         "met': it is what 1,581 of 1,582 records look like")

    def test_the_old_boolean_still_reads_false_which_is_why_this_exists(self):
        """The control that proves the defect was real and is not imagined.

        `prior_contact` is unchanged - other callers license 'as discussed' off
        it - so this asserts the two answers now DIFFER for the same input: the
        boolean says "no history" and the authority says "nobody knows".
        """
        self.assertIsNone(claims.prior_contact(record(), CONTACT))
        self.assertFalse(bool(claims.prior_contact(record(), CONTACT)))
        self.assertNotEqual(claims.NOT_CONTACTED,
                            claims.prior_contact_state(record(), CONTACT))

    def test_a_confirmed_local_touch_still_settles_it_yes(self):
        """The local log may only ever say YES, and it still does."""
        for kind in claims.PRIOR_CONTACT_EVENTS:
            with self.subTest(event=kind):
                rec = record([{"type": kind, "contact": "dana"}])
                self.assertEqual(claims.CONTACTED,
                                 claims.prior_contact_state(rec, CONTACT))
                self.assertFalse(claims.may_claim_first_contact(rec, CONTACT))

    def test_a_colleagues_event_is_not_this_persons_history(self):
        """Unchanged behaviour, asserted so the rewrite did not lose it."""
        rec = record([{"type": "email_delivered", "contact": "somebody-else"}])
        self.assertEqual(claims.PRIOR_CONTACT_UNKNOWN,
                         claims.prior_contact_state(rec, CONTACT))


class OnlyAProvenNegativeLicensesFirstContact(QueueTest):

    def test_an_answered_and_absent_lookup_on_both_channels_is_proven(self):
        """The canary's own case, and the only one that licenses the claim."""
        self.assertEqual(claims.NOT_CONTACTED,
                         claims.prior_contact_state(record(), CONTACT,
                                                    absent_everywhere()))
        self.assertTrue(claims.may_claim_first_contact(record(), CONTACT,
                                                       absent_everywhere()))

    def test_a_manual_send_makes_it_contacted_however_old(self):
        """"You have not met them" is false whoever sent the email."""
        for days in (1, 200, 900):
            with self.subTest(days=days):
                dos = dossier(cold_baseline(days=days))
                self.assertEqual(claims.CONTACTED,
                                 claims.prior_contact_state(record(), CONTACT,
                                                            dos))
                self.assertFalse(claims.may_claim_first_contact(
                    record(), CONTACT, dos))

    def test_a_resonate_os_send_makes_it_contacted(self):
        """A STARI LEAD is the other half of the class this defect bit."""
        dos = dossier(email_side([membership(OURS, "sequence_finished",
                                            emails_sent=1)],
                                 sent_rows=[sent_row(OURS, 40)]))
        self.assertEqual(claims.CONTACTED,
                         claims.prior_contact_state(record(), CONTACT, dos))

    def test_a_linkedin_message_alone_makes_it_contacted(self):
        """The email estate being clean is not the whole history."""
        dos = dossier(absent_everywhere()["email"],
                      linkedin_side(rows=[conversation(40)]))
        self.assertEqual(claims.CONTACTED,
                         claims.prior_contact_state(record(), CONTACT, dos))

    def test_a_membership_with_no_dated_send_is_unknown_not_a_clean_sheet(self):
        """"Loaded as a lead, nothing sent yet" cannot license the claim.

        `check_address` already reports that state as a touch rather than a
        clean sheet. Somebody queued this person; the queue may have flushed.
        """
        dos = dossier(email_side([membership(MANUAL, "sequence_finished",
                                            emails_sent=0)],
                                 sent_rows=()))
        self.assertEqual(claims.PRIOR_CONTACT_UNKNOWN,
                         claims.prior_contact_state(record(), CONTACT, dos))
        self.assertFalse(claims.may_claim_first_contact(record(), CONTACT, dos))

    def test_a_reply_or_a_bounce_is_a_touch_by_construction(self):
        """Something reached them for them to answer it or for it to bounce."""
        for status in (collision.REPLIED, collision.BOUNCED):
            with self.subTest(status=status):
                dos = dossier(email_side([membership(MANUAL, status,
                                                     emails_sent=1)],
                                         sent_rows=[sent_row(MANUAL, 300)]))
                self.assertEqual(claims.CONTACTED,
                                 claims.prior_contact_state(record(), CONTACT,
                                                            dos))


class OneUnreadableChannelIsEnoughToRefuse(QueueTest):

    def test_an_unreadable_lookup_on_either_channel_is_unknown(self):
        """A person somebody wrote to on LinkedIn has still been written to."""
        for answer in (collision.LOOKUP_FAILED, collision.LOOKUP_PARTIAL,
                       collision.LOOKUP_NOT_ASKED):
            with self.subTest(email=answer):
                dos = dossier(email_side([membership(MANUAL,
                                                     "sequence_finished",
                                                     emails_sent=1)],
                                         sent_rows=[sent_row(MANUAL, 300)],
                                         lookup=answer))
                self.assertEqual(claims.PRIOR_CONTACT_UNKNOWN,
                                 claims.prior_contact_state(record(), CONTACT,
                                                            dos))
            with self.subTest(linkedin=answer):
                dos = dossier(absent_everywhere()["email"],
                              linkedin_side(lookup=answer))
                self.assertEqual(claims.PRIOR_CONTACT_UNKNOWN,
                                 claims.prior_contact_state(record(), CONTACT,
                                                            dos))

    def test_a_lead_with_no_linkedin_identifier_is_unknown(self):
        dos = dossier(absent_everywhere()["email"],
                      linkedin_side(rows=(), slug=None))
        self.assertEqual(claims.PRIOR_CONTACT_UNKNOWN,
                         claims.prior_contact_state(record(), CONTACT, dos))

    def test_a_send_history_that_does_not_reconcile_is_unknown(self):
        """The fifteen-row trap reaches the COPY layer too.

        Fifteen dated sends against a provider claim of twenty-three: one of the
        eight undated could be yesterday, so neither "we have not met" nor "as
        discussed" is safe to write.
        """
        dos = dossier(email_side([membership(MANUAL, "sequence_finished",
                                            emails_sent=23)], emails_sent=23,
                                 sent_rows=[sent_row(MANUAL, 40 + 5 * i)
                                            for i in range(15)]))
        self.assertEqual(claims.PRIOR_CONTACT_UNKNOWN,
                         claims.prior_contact_state(record(), CONTACT, dos))

    def test_an_ambiguous_or_unverified_status_is_unknown(self):
        for status in (collision.STOPPED, "never_contacted", "warming"):
            with self.subTest(status=status):
                dos = dossier(email_side([membership(MANUAL, status,
                                                     emails_sent=1)],
                                         sent_rows=[sent_row(MANUAL, 300)]))
                self.assertEqual(claims.PRIOR_CONTACT_UNKNOWN,
                                 claims.prior_contact_state(record(), CONTACT,
                                                            dos))

    def test_an_undatable_linkedin_thread_is_unknown(self):
        dos = dossier(absent_everywhere()["email"],
                      linkedin_side(rows=[conversation(300,
                                                       last_message_at=None)]))
        self.assertEqual(claims.PRIOR_CONTACT_UNKNOWN,
                         claims.prior_contact_state(record(), CONTACT, dos))

    def test_every_state_is_reachable_and_they_are_distinct(self):
        """A tri-state with an unreachable branch is a boolean with a typo."""
        seen = {
            claims.prior_contact_state(record(), CONTACT),
            claims.prior_contact_state(record(), CONTACT, absent_everywhere()),
            claims.prior_contact_state(record(), CONTACT,
                                       dossier(cold_baseline())),
        }
        self.assertEqual(set(claims.PRIOR_CONTACT_STATES), seen)


class ThePromptNoLongerAssertsItEither(QueueTest):
    """The prompt is the thing that reached a person, so it is asserted too."""

    def draft(self):
        """The prompt as the MODEL reads it: one line, whitespace collapsed.

        Searched against the collapsed form because the file is hard-wrapped at
        79 columns, so "we have not met" is stored as "we have
  not met" and a
        naive `in` check misses a phrase that is plainly present. The model sees
        the sentence, not the line breaks, so the test should too - the first
        run of this file failed on exactly that and the prompt was correct.
        """
        import os
        import re
        here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        with open(os.path.join(here, "prompts", "draft.md"),
                  encoding="utf-8") as handle:
            return re.sub(r"\s+", " ", handle.read())

    def test_the_false_sentence_is_gone(self):
        """Asserted on the artefact that reached a real inbox.

        This is a text assertion and it is the right kind: the defect WAS the
        text, it was generated verbatim from this file, and no behavioural
        assertion reaches an LLM instruction.
        """
        body = self.draft()
        self.assertNotIn("you have not met them", body.lower())
        self.assertNotIn("you have not failed", body.lower())

    def test_the_unknown_branch_exists_and_forbids_both_kinds_of_claim(self):
        """A third branch that only forbade "as discussed" would be half a fix."""
        body = self.draft()
        self.assertIn("unknown", body.lower())
        low = body.lower()
        for forbidden in ("we have not met", "reaching out for the first time",
                          "this is my first time writing"):
            self.assertIn(forbidden, low,
                          f"the unknown branch must name {forbidden!r} as "
                          f"forbidden, or the model will write it")
        self.assertIn("as discussed", low)

    def test_the_boolean_form_is_mapped_to_unknown_not_to_a_negative(self):
        """Until `generate.py` passes the state, `false` still arrives."""
        body = self.draft()
        self.assertIn("`prior_contact: false`", body)
        window = body[body.index("`prior_contact: false`"):][:300].lower()
        self.assertIn("unknown", window,
                      "a boolean false must be read as unknown, because that "
                      "is what it actually means on this estate")
