#!/usr/bin/env python3
"""Client reports: the document a workspace's results leave the building in.

Three templates, and the difference between them is who may read them rather
than how much detail they carry:

  EXECUTIVE     what a client's leadership needs. Outcomes, no machinery.
  DETAILED      the same, plus every audience breakdown the data supports.
  INTERNAL      operations. Provider usage, verification waterfall, MX,
                holds, jobs. Never leaves Resonate.

The rules the whole module is built to:

**Every number comes from `src/report.py`.** Nothing here counts anything
itself. A report that recomputes a funnel is a second definition of the
funnel, and the second one is the one that goes stale - so the same
`report.for_client` and `report.funnel_for` that the web dashboards read are
what fills these pages. "The report says something different from the screen"
is not a bug this product will have.

**A number nobody can know is named, never zeroed.** `report.unavailable()`
lists them, and a section whose data is unavailable prints the reason. A
client report showing "Meetings: 0" when nothing observes a calendar is a lie
that takes one meeting to discover.

**INTERNAL never renders from a client-facing request.** The template is
chosen server-side against a permission, not from a form field the browser
sends - see `src/web/api.py`.

**Observations are deterministic.** The Observations section is generated by
comparing counted values against stated thresholds, in `observations()`. No
model writes a strategic conclusion into a document a client will read.
"""
import datetime

from . import pdf, report, store

# ---------------------------------------------------------------- templates

EXECUTIVE = "executive"
MONTHLY = "monthly"
DETAILED = "detailed"
INTERNAL = "internal"
TEMPLATES = (EXECUTIVE, MONTHLY, DETAILED, INTERNAL)

TEMPLATE_LABEL = {
    EXECUTIVE: "Executive Report",
    MONTHLY: "Resonate Outbound Performance Report",
    DETAILED: "Deep-Dive Performance Report",
    INTERNAL: "Internal Operations Report",
}

TEMPLATE_BLURB = {
    EXECUTIVE: "Two minutes. Outcomes for a client's leadership, and nothing "
               "about the machine.",
    MONTHLY: "The canonical monthly deliverable. Funnel, channels, campaigns, "
             "replies, pipeline, audience, senders, month-over-month, and "
             "what happens next.",
    DETAILED: "Everything in the monthly report, plus every audience "
              "breakdown the data supports.",
    INTERNAL: "Operations. Provider usage, verification, MX, holds and jobs. "
              "Resonate only.",
}

# Section key -> (label, which templates offer it, is it client-safe).
#
# The third column is the one that matters. A section that is not client-safe
# cannot be switched on for an executive or detailed report at all - it is not
# a default that somebody could flip, it is absent from those templates.
CLIENT_FACING = (EXECUTIVE, MONTHLY, DETAILED)
EVERY = (EXECUTIVE, MONTHLY, DETAILED, INTERNAL)

SECTIONS = (
    ("summary", "Executive Summary", EVERY, True),
    ("takeaways", "Key Takeaways", (MONTHLY, DETAILED), True),
    ("funnel", "Outbound Funnel", EVERY, True),
    ("email", "Email Performance", (MONTHLY, DETAILED, INTERNAL), True),
    ("linkedin", "LinkedIn Performance", (MONTHLY, DETAILED, INTERNAL), True),
    ("channels", "Multichannel Performance", EVERY, True),
    ("campaigns", "Campaign Performance", EVERY, True),
    ("replies", "Reply Analysis", EVERY, True),
    ("pipeline", "Pipeline", (MONTHLY, DETAILED), True),
    ("positive", "Positive Replies", EVERY, True),
    ("accounts", "Account Engagement", (MONTHLY, DETAILED), True),
    ("personas", "Persona Performance", CLIENT_FACING, True),
    ("angles", "Message Angle Performance", (DETAILED,), True),
    ("audience", "Audience Breakdown", (MONTHLY, DETAILED), True),
    ("geography", "Geography", (MONTHLY, DETAILED), True),
    ("senders", "Sender Performance", (MONTHLY, DETAILED, INTERNAL), True),
    ("trend", "Month over Month", (MONTHLY, DETAILED), True),
    ("meetings", "Meetings", CLIENT_FACING, True),
    ("learned", "What We Learned", (MONTHLY, DETAILED), True),
    ("next", "Next Month", (MONTHLY, DETAILED), True),
    ("observations", "Observations", (EXECUTIVE, DETAILED), True),
    ("verification", "Verification", (INTERNAL,), False),
    ("security", "Email Security and MX", (INTERNAL,), False),
    ("providers", "Provider Usage", (INTERNAL,), False),
    ("operations", "Operations", (INTERNAL,), False),
    ("appendix", "Appendix: What This Report Cannot Measure", EVERY, True),
)

SECTION_LABEL = {key: label for key, label, _, _ in SECTIONS}
CLIENT_SAFE_SECTIONS = {key for key, _, _, safe in SECTIONS if safe}


def sections_for(template):
    """Which sections this template may contain, in order."""
    return [key for key, _, templates, _ in SECTIONS if template in templates]


def default_sections(template):
    """What is on unless somebody turns it off.

    Everything the template offers. A default that hides a section is a
    default that quietly changes what a client is told, and the place to make
    that decision is the workspace's report settings, visibly.
    """
    return list(sections_for(template))


def resolve_sections(template, requested=None):
    """The sections that will actually render.

    A key the template does not offer is dropped rather than honoured. That is
    the guard that stops `sections=providers` on an executive report from
    putting the verification waterfall in front of a client - the template
    decides what exists, and the request only narrows it.
    """
    allowed = sections_for(template)
    # An empty request means the template's defaults, not an empty document.
    # A form submits nothing at all for a checkbox group where every box is
    # cleared, and honouring that literally produced a one-page PDF with a
    # cover and no report - which looks like a broken product rather than
    # like a choice somebody made.
    if not requested:
        return list(allowed)
    wanted = {str(s).strip() for s in requested if str(s).strip()}
    if not wanted:
        return list(allowed)
    return [key for key in allowed if key in wanted]


# ------------------------------------------------------------------ palette
#
# The document's colours, as PDF fractions. Kept in step with the web app's
# tokens in `src/web/assets.py` by `DESIGN-SYSTEM.md`, which is the one place
# the brand is written down.

INK = (0.09, 0.11, 0.16)
MUTED = (0.42, 0.46, 0.55)
FAINT = (0.62, 0.66, 0.73)
RULE = (0.87, 0.89, 0.92)
BAND = (0.96, 0.97, 0.98)
BRAND = (0.09, 0.32, 0.78)
BRAND_DEEP = (0.05, 0.15, 0.40)
GOOD = (0.06, 0.50, 0.34)
WARN = (0.72, 0.47, 0.05)
BAD = (0.70, 0.16, 0.16)

LEFT = pdf.MARGIN
RIGHT = pdf.A4[0] - pdf.MARGIN
WIDTH = RIGHT - LEFT


# ------------------------------------------------------------------- layout

class Canvas:
    """A cursor down a page, which starts a new one when it runs out.

    Every draw call returns through here rather than touching `pdf.Page`
    directly, so page breaks happen in one place. A section that draws its own
    pages is a section that eventually writes over a footer.
    """

    def __init__(self, document, meta):
        self.doc = document
        self.meta = meta
        self.page = None
        self.y = 0.0
        self.numbered = []
        self.new_page()

    def new_page(self, first=False):
        self.page = self.doc.page()
        self.y = pdf.CONTENT_TOP
        if not first:
            self.numbered.append(self.page)
            self._running_head()
        return self.page

    def _running_head(self):
        self.page.text(LEFT, 806, self.meta["workspace_name"],
                       pdf.HELV_BOLD, 8.5, MUTED)
        self.page.text_right(RIGHT, 806, self.meta["title"], pdf.HELV, 8.5,
                             MUTED)
        self.page.line(LEFT, 800, RIGHT, 800, RULE, 0.6)

    def space(self, amount):
        self.y -= amount
        return self

    def need(self, amount):
        """Break before drawing something that will not fit.

        Called with the height of the *whole* block - a heading plus its first
        rows - so a heading is never orphaned at the bottom of a page.
        """
        if self.y - amount < pdf.CONTENT_BOTTOM:
            self.new_page()
        return self

    # -- primitives

    def heading(self, text, size=15.0):
        self.need(48)
        self.space(6)
        self.page.text(LEFT, self.y, text, pdf.HELV_BOLD, size, INK)
        self.y -= 8
        self.page.line(LEFT, self.y, RIGHT, self.y, BRAND, 1.4)
        self.y -= 16
        return self

    def subheading(self, text):
        self.need(30)
        self.space(4)
        self.page.text(LEFT, self.y, text, pdf.HELV_BOLD, 10.5, INK)
        self.y -= 14
        return self

    def paragraph(self, text, size=9.5, colour=INK, font=pdf.HELV,
                  leading=13.0, indent=0.0):
        for line in pdf.wrap(text, WIDTH - indent, font, size):
            self.need(leading + 2)
            self.page.text(LEFT + indent, self.y, line, font, size, colour)
            self.y -= leading
        return self

    def note(self, text):
        return self.paragraph(text, 8.5, MUTED, pdf.HELV_OBLIQUE, 11.0)

    def bullet(self, text, colour=INK):
        lines = pdf.wrap(text, WIDTH - 16, pdf.HELV, 9.5)
        for index, line in enumerate(lines):
            self.need(14)
            if index == 0:
                self.page.rect(LEFT + 2, self.y + 3, 3, 3, colour)
            self.page.text(LEFT + 16, self.y, line, pdf.HELV, 9.5, INK)
            self.y -= 13
        return self

    def metrics(self, pairs, per_row=4):
        """A row of headline figures. The one shape a reader scans first."""
        pairs = [p for p in pairs if p is not None]
        for start in range(0, len(pairs), per_row):
            chunk = pairs[start:start + per_row]
            self.need(58)
            box = WIDTH / per_row
            for index, (label, value, hint) in enumerate(chunk):
                x = LEFT + index * box
                self.page.rect(x, self.y - 40, box - 8, 48, BAND)
                self.page.rect(x, self.y - 40, 2.5, 48, BRAND)
                self.page.text(x + 10, self.y - 2,
                               pdf.truncate(str(value), box - 26,
                                            pdf.HELV_BOLD, 17),
                               pdf.HELV_BOLD, 17, BRAND_DEEP)
                self.page.text(x + 10, self.y - 18,
                               pdf.truncate(label, box - 26, pdf.HELV, 8),
                               pdf.HELV, 8, MUTED)
                if hint:
                    self.page.text(x + 10, self.y - 30,
                                   pdf.truncate(hint, box - 26, pdf.HELV, 7),
                                   pdf.HELV, 7, FAINT)
            self.y -= 56
        return self

    def table(self, headers, rows, widths=None, aligns=None, note=None):
        """A table that breaks across pages and repeats its header when it does.

        A continued table with no header is a grid of unlabelled numbers, and
        that is exactly the page somebody screenshots and misreads.
        """
        count = len(headers)
        widths = widths or [WIDTH / count] * count
        aligns = aligns or (["l"] + ["r"] * (count - 1))

        def draw_header():
            self.need(26)
            self.page.rect(LEFT, self.y - 6, WIDTH, 18, BAND)
            x = LEFT
            for index, head in enumerate(headers):
                if aligns[index] == "r":
                    self.page.text_right(x + widths[index] - 6, self.y,
                                         head, pdf.HELV_BOLD, 8.5, MUTED)
                else:
                    self.page.text(x + 6, self.y,
                                   pdf.truncate(head, widths[index] - 12,
                                                pdf.HELV_BOLD, 8.5),
                                   pdf.HELV_BOLD, 8.5, MUTED)
                x += widths[index]
            self.y -= 20

        draw_header()
        if not rows:
            self.need(20)
            self.page.text(LEFT + 6, self.y, "No rows for this period.",
                           pdf.HELV_OBLIQUE, 9, MUTED)
            self.y -= 16
            return self

        for row in rows:
            if self.y - 16 < pdf.CONTENT_BOTTOM:
                self.new_page()
                draw_header()
            x = LEFT
            for index, cell in enumerate(row):
                value = "" if cell is None else str(cell)
                if aligns[index] == "r":
                    self.page.text_right(x + widths[index] - 6, self.y, value,
                                         pdf.HELV, 9, INK)
                else:
                    self.page.text(x + 6, self.y,
                                   pdf.truncate(value, widths[index] - 12,
                                                pdf.HELV, 9),
                                   pdf.HELV, 9, INK)
                x += widths[index]
            self.y -= 6
            self.page.line(LEFT, self.y, RIGHT, self.y, RULE, 0.4)
            self.y -= 10
        if note:
            self.space(2)
            self.note(note)
        return self

    def bars(self, rows, unit=""):
        """A horizontal bar chart. Vector, so it stays sharp at any zoom.

        Every bar prints its own value. A chart whose bars can only be read
        against an axis is a chart somebody reads wrong.
        """
        rows = [(str(label), value) for label, value in rows
                if isinstance(value, (int, float))]
        if not rows:
            return self.note("Nothing to chart for this period.")
        top = max((v for _, v in rows), default=0) or 1
        label_w = 150.0
        value_w = 60.0
        track = WIDTH - label_w - value_w
        for label, value in rows:
            self.need(18)
            self.page.text(LEFT, self.y, pdf.truncate(label, label_w - 8),
                           pdf.HELV, 9, INK)
            self.page.rect(LEFT + label_w, self.y - 2, track, 9, BAND)
            filled = max(1.0, track * (float(value) / float(top)))
            self.page.rect(LEFT + label_w, self.y - 2, filled, 9, BRAND)
            self.page.text_right(RIGHT, self.y, f"{value:,}{unit}",
                                 pdf.HELV_BOLD, 9, INK)
            self.y -= 17
        return self

    def unavailable(self, why):
        self.need(26)
        self.page.rect(LEFT, self.y - 8, 2.5, 20, WARN)
        self.page.text(LEFT + 10, self.y, "Not tracked", pdf.HELV_BOLD, 9,
                       WARN)
        self.y -= 13
        self.paragraph(why, 8.5, MUTED, pdf.HELV_OBLIQUE, 11.0, indent=10)
        return self


# --------------------------------------------------------------- formatting

def _n(value):
    """A count. `None` is "not tracked" and never renders as a number."""
    if value is None:
        return "n/a"
    try:
        return f"{int(value):,}"
    except (TypeError, ValueError):
        return str(value)


def _rate(numerator, denominator):
    """A percentage that always travels with the fraction it came from.

    "12%" is a claim. "12% (6/50)" is a claim somebody can check, and a
    denominator of fifty is the part a reader needs in order to not build a
    strategy on it.
    """
    if not denominator:
        return "n/a"
    if numerator is None:
        return "n/a"
    return f"{(100.0 * numerator / denominator):.1f}% ({numerator:,}/{denominator:,})"


def _period_label(start, end):
    if start and end:
        return f"{start} to {end}"
    if start:
        return f"From {start}"
    if end:
        return f"Up to {end}"
    return "All time"


# ------------------------------------------------------------- observations

# The thresholds an observation is allowed to be made against. Written down
# rather than chosen in the prose, so "we said their reply rate was low"
# always means the same thing, and so changing the bar is one visible edit.
THRESHOLDS = {
    "held_share_high": 0.25,
    "linkedin_only_share_high": 0.35,
    "small_sample": 30,
}


def observations(data):
    """Deterministic notes on the numbers. No model writes these.

    Each one is a comparison against `THRESHOLDS` with the figures attached.
    An observation a client can check against the table above it is worth
    printing; a generated sentence about "strong momentum in the DACH region"
    is worth less than nothing, because somebody will act on it.
    """
    out = []
    funnel = data.get("funnel") or {}
    contacts = data.get("contacts_found") or 0
    selected = data.get("contacts_selected") or 0
    reachable = data.get("contacts_email_reachable")
    if reachable is None:                       # older stored data
        reachable = data.get("contacts_verified") or 0
    replies = data.get("replies") or 0
    positive = data.get("positive_replies") or 0
    pushed = data.get("emails_pushed") or 0
    linkedin_only = data.get("contacts_linkedin_only") or 0
    # Contacts that *have* an address and cannot be written to. The
    # subtraction used to start from every contact found, which put every
    # contact with no address at all and every LinkedIn-only person into a
    # number explained as verification failure, disagreement or email
    # security - three reasons that describe none of them.
    with_address = (data.get("confirmation") or {}).get(
        "contacts_with_an_address")
    held = max(0, (with_address if with_address is not None
                   else data.get("contacts_found") or 0) - reachable)

    if not pushed:
        out.append(("info",
                    "No outreach has been confirmed sent in this period, so "
                    "no reply rate can be reported. Every figure below "
                    "describes the audience that was built, not its "
                    "performance."))
    if contacts and held / float(contacts) > THRESHOLDS["held_share_high"]:
        out.append(("warn",
                    f"{held:,} of {contacts:,} contacts "
                    f"({100.0 * held / contacts:.0f}%) have an address that "
                    f"cannot be used rather than being "
                    f"contactable by email. That means the address failed "
                    f"verification, the two verifiers disagreed, or email "
                    f"security ruled the domain out - none of them is a "
                    f"delivery failure, and none was guessed past."))
    if contacts and linkedin_only / float(contacts) > \
            THRESHOLDS["linkedin_only_share_high"]:
        out.append(("info",
                    f"{linkedin_only:,} contacts are reachable on LinkedIn "
                    f"only. LinkedIn capacity, not list size, is the limit on "
                    f"this segment."))
    if pushed and replies:
        out.append(("info",
                    f"Reply rate {_rate(replies, pushed)} against confirmed "
                    f"sends."))
    if replies and positive:
        out.append(("good",
                    f"Positive replies {_rate(positive, replies)} of all "
                    f"replies."))
    if 0 < pushed < THRESHOLDS["small_sample"]:
        out.append(("warn",
                    f"Only {pushed:,} confirmed sends in this period. That is "
                    f"below the {THRESHOLDS['small_sample']} this report "
                    f"treats as a readable sample, so no rate here should be "
                    f"used to compare segments."))
    if funnel.get("qualified") is not None and data.get("domains_uploaded"):
        out.append(("info",
                    f"ICP qualification kept "
                    f"{_rate(data.get('domains_qualified'), data.get('domains_uploaded'))} "
                    f"of uploaded domains."))
    if not out:
        out.append(("info",
                    "Nothing in this period crosses a threshold this report "
                    "comments on."))
    return out


# ------------------------------------------------------------------ sections

def _cover(canvas, meta):
    page = canvas.page
    page.rect(0, 690, pdf.A4[0], 152, BRAND_DEEP)
    page.rect(0, 684, pdf.A4[0], 6, BRAND)
    page.text(LEFT, 786, "RESONATE GROUP", pdf.HELV_BOLD, 19, (1, 1, 1))
    page.text(LEFT, 766, "Outbound Operations", pdf.HELV, 10.5,
              (0.75, 0.82, 0.95))
    page.text(LEFT, 716, meta["template_label"].upper(), pdf.HELV_BOLD, 9,
              (0.62, 0.74, 0.95))

    canvas.y = 610
    canvas.page.text(LEFT, canvas.y, meta["workspace_name"], pdf.HELV_BOLD,
                     30, INK)
    canvas.y -= 30
    canvas.page.text(LEFT, canvas.y, meta["template_label"], pdf.HELV, 15,
                     MUTED)
    canvas.y -= 40
    canvas.page.line(LEFT, canvas.y, LEFT + 90, canvas.y, BRAND, 2.5)
    canvas.y -= 34

    for label, value in (("Reporting period", meta["period"]),
                         ("Workspace", meta["workspace_slug"]),
                         ("Campaigns", meta["campaign_label"]),
                         ("Prepared", meta["generated_at"]),
                         ("Prepared by", meta["generated_by"]),
                         ("Report ID", meta["report_id"])):
        canvas.page.text(LEFT, canvas.y, label.upper(), pdf.HELV_BOLD, 7.5,
                         FAINT)
        canvas.page.text(LEFT + 150, canvas.y, str(value), pdf.HELV, 10, INK)
        canvas.y -= 20

    if meta.get("demo"):
        canvas.y -= 16
        canvas.page.rect(LEFT, canvas.y - 22, WIDTH, 34, (1.0, 0.96, 0.88))
        canvas.page.rect(LEFT, canvas.y - 22, 3, 34, WARN)
        canvas.page.text(LEFT + 12, canvas.y, "DEMONSTRATION DATA",
                         pdf.HELV_BOLD, 9.5, WARN)
        canvas.page.text(LEFT + 12, canvas.y - 14,
                         "Fictional companies and people. Not a record of "
                         "real outreach.", pdf.HELV, 8.5, MUTED)

    canvas.page.text(LEFT, 96,
                     "Confidential. Prepared by Resonate Group for the named "
                     "client.", pdf.HELV, 8, FAINT)
    canvas.page.line(LEFT, 84, RIGHT, 84, RULE, 0.6)
    canvas.page.text(LEFT, 70,
                     "Every figure in this report is counted from recorded "
                     "events. Figures this system cannot observe are named in "
                     "the appendix rather than shown as zero.",
                     pdf.HELV_OBLIQUE, 7.5, MUTED)


def _summary(canvas, data, meta):
    canvas.heading("Executive Summary")
    written = ((meta or {}).get("narrative") or {}).get("summary")
    if written:
        # A person wrote this. It replaces the generated sentence and
        # replaces nothing else - every figure below is still counted.
        canvas.paragraph(written)
        canvas.space(6)
        canvas.metrics([
            ("Companies", _n(data.get("domains_uploaded")), "assessed"),
            ("Contacts", _n(data.get("contacts_found")), "found"),
            ("Contactable", _n(_reachable(data)), "verified"),
            ("Confirmed sent", _n(data.get("emails_pushed")), "touches"),
        ])
        canvas.metrics([
            ("Replies", _n(data.get("replies")), "all classifications"),
            ("Positive replies", _n(data.get("positive_replies")),
             "reviewed"),
            ("Meetings", _n(data.get("meetings")),
             "not tracked" if data.get("meetings") is None else "recorded"),
        ], per_row=3)
        return
    canvas.paragraph(
        f"This report covers {meta['workspace_name']} for "
        f"{meta['period'].lower()}. "
        f"{_n(data.get('domains_uploaded'))} companies were assessed against "
        f"the workspace's ICP, producing "
        f"{_n(data.get('contacts_found'))} contacts, of which "
        f"{_n(_reachable(data))} are contactable by email after "
        f"double verification and email-security screening.")
    canvas.space(6)
    canvas.metrics([
        ("Companies", _n(data.get("domains_uploaded")), "uploaded"),
        ("ICP qualified", _n(data.get("domains_qualified")), "kept"),
        ("Contacts", _n(data.get("contacts_found")), "found"),
        ("Contactable", _n(_reachable(data)), "email verified"),
    ])
    canvas.metrics([
        ("Confirmed sent", _n(data.get("emails_pushed")), "email touches"),
        ("Replies", _n(data.get("replies")), "all classifications"),
        ("Positive replies", _n(data.get("positive_replies")), "reviewed"),
        ("Meetings", _n(data.get("meetings")),
         "not tracked" if data.get("meetings") is None else "recorded"),
    ])


def _funnel(canvas, data):
    canvas.heading("Outbound Funnel")
    canvas.paragraph(
        "Each stage is counted from stored records and events. A stage this "
        "system does not observe is named rather than inferred from the stage "
        "before it.")
    canvas.space(8)
    uploaded = data.get("domains_uploaded") or 0
    stages = [
        ("Domains uploaded", data.get("domains_uploaded"), None),
        ("ICP qualified", data.get("domains_qualified"), uploaded),
        ("Contacts found", data.get("contacts_found"), None),
        ("Contacts selected", data.get("contacts_selected"),
         data.get("contacts_found")),
        ("Contactable by email", _reachable(data),
         data.get("contacts_selected")),
        ("Confirmed sent", data.get("emails_pushed"), _reachable(data)),
        ("Replied", data.get("replies"), data.get("emails_pushed")),
        ("Positive reply", data.get("positive_replies"), data.get("replies")),
        ("Meeting", data.get("meetings"), data.get("positive_replies")),
    ]
    rows = [(label, _n(value),
             _rate(value, previous) if previous else "-")
            for label, value, previous in stages]
    canvas.table(["Stage", "Count", "Conversion from previous"],
                 rows, [WIDTH * 0.44, WIDTH * 0.18, WIDTH * 0.38],
                 ["l", "r", "r"],
                 note="Every conversion states its own numerator and "
                      "denominator. A percentage without them is not a "
                      "measurement.")
    canvas.space(8)
    canvas.bars([(label, value) for label, value, _ in stages
                 if isinstance(value, int)])


def _campaigns(canvas, data):
    canvas.heading("Campaign Performance")
    rows = []
    for campaign in data.get("campaign_rows") or []:
        rows.append((
            campaign.get("name") or campaign.get("campaign_id"),
            _humanise(campaign.get("status")),
            _n(campaign.get("companies")),
            _n(campaign.get("contacts")),
            _n(campaign.get("sent")),
            _n(campaign.get("replies")),
            _n(campaign.get("positive")),
        ))
    canvas.table(
        ["Campaign", "Status", "Companies", "Contacts", "Sent", "Replies",
         "Positive"],
        rows,
        # The name and the status carry words; the rest carry small integers.
        [WIDTH * 0.32, WIDTH * 0.18, WIDTH * 0.10, WIDTH * 0.10,
         WIDTH * 0.10, WIDTH * 0.10, WIDTH * 0.10],
        ["l", "l", "r", "r", "r", "r", "r"])


def _channels(canvas, data):
    canvas.heading("Multichannel Performance")
    canvas.paragraph(
        "Contacts are grouped by the channels they are reachable on, which is "
        "decided by verification and email-security screening rather than by "
        "preference.")
    canvas.space(6)
    canvas.bars([
        ("Email and LinkedIn", data.get("contacts_multichannel") or 0),
        ("Email only", data.get("contacts_email_only") or 0),
        ("LinkedIn only", data.get("contacts_linkedin_only") or 0),
    ])
    canvas.space(8)
    canvas.note(
        "Where a contact received a multichannel sequence, a reply is not "
        "attributed to the last channel alone. The touch history behind each "
        "reply is in the Web App.")


def _breakdown_table(canvas, title, mapping, note=None, subheading=True):
    # `subheading` is off where the section heading already carries the word.
    # "Persona Performance" over "Persona" over a column headed "Persona" is
    # the same word three times before a single number.
    if subheading:
        canvas.subheading(title)
    rows = []
    for key, value in sorted((mapping or {}).items(),
                             key=lambda kv: (-_as_count(kv[1]), str(kv[0]))):
        rows.append((_humanise(key), _n(_as_count(value))))
    canvas.table([title, "Contacts"], rows,
                 [WIDTH * 0.68, WIDTH * 0.32], ["l", "r"], note=note)


def _plural(count, one, many):
    """"1 company", not "1 companies"."""
    count = count or 0
    return f"{count:,} {one if count == 1 else many}"


def _humanise(key):
    """An internal key as a person reads it: `economic_buyer` -> Economic buyer.

    A client's document is not the place a reader meets this system's
    identifiers. Anything already written for people is left alone.
    """
    text = str(key)
    if "_" not in text:
        return text
    return text.replace("_", " ").strip().capitalize()


def _as_count(value):
    if isinstance(value, dict):
        for key in ("contacts", "count", "total", "n"):
            if isinstance(value.get(key), int):
                return value[key]
        return 0
    return value if isinstance(value, int) else 0


def _personas(canvas, data):
    canvas.heading("Persona Performance")
    _breakdown_table(canvas, "Persona", data.get("by_persona"),
                     note="Sample sizes travel with every persona. A persona "
                          "with a handful of contacts is not evidence about "
                          "a persona.",
                     subheading=False)


def _angles(canvas, data):
    canvas.heading("Message Angle Performance")
    _breakdown_table(canvas, "Angle", data.get("by_angle"),
                     subheading=False)


def _audience(canvas, data):
    canvas.heading("Audience Breakdown")
    for label, key in (("Vertical", "by_vertical"),
                       ("Industry", "by_industry"),
                       ("Country", "by_country"),
                       ("Company size", "by_size"),
                       ("ICP tier", "by_tier")):
        if data.get(key):
            _breakdown_table(canvas, label, data[key])
            canvas.space(4)
    if not any(data.get(k) for k in ("by_vertical", "by_industry",
                                     "by_country", "by_size", "by_tier")):
        canvas.unavailable(
            "No audience dimension has been populated for this workspace yet. "
            "These break down once companies carry qualification evidence.")


def _replies(canvas, data):
    canvas.heading("Reply Analysis")
    breakdown = data.get("reply_breakdown") or {}
    total = data.get("replies") or 0
    # `_humanise` leaves a word with no underscore alone - it assumes anything
    # already written for people needs no help - so a single-word key like
    # `positive` came back lowercase. These are dict keys, not prose, so the
    # capital is added here rather than by widening `_humanise` for callers
    # that are passing real text.
    rows = [(_humanise(k).capitalize(), _n(v), _rate(v, total))
            for k, v in sorted(breakdown.items(),
                               key=lambda kv: -(kv[1] or 0))]
    canvas.table(["Classification", "Count", "Share of replies"], rows,
                 [WIDTH * 0.44, WIDTH * 0.20, WIDTH * 0.36],
                 ["l", "r", "r"])
    canvas.space(6)
    canvas.paragraph(
        f"{_plural(data.get('companies_paused'), 'company', 'companies')} "
        f"{'is' if (data.get('companies_paused') or 0) == 1 else 'are'} "
        f"paused. Any reply pauses every channel for the whole company, so "
        f"nobody on the list is contacted again after somebody has "
        f"answered.")


def _positive(canvas, data):
    canvas.heading("Positive Replies")
    canvas.metrics([
        ("Positive replies", _n(data.get("positive_replies")), "reviewed"),
        ("Of all replies", _rate(data.get("positive_replies"),
                                 data.get("replies") or 0), ""),
        ("Companies paused", _n(data.get("companies_paused")), "both channels"),
    ], per_row=3)
    canvas.space(4)
    canvas.paragraph(
        "A reply is classified conservatively. An ambiguous message is left "
        "for a person rather than counted as positive, so this figure "
        "understates rather than flatters.")


def _meetings(canvas, data):
    canvas.heading("Meetings")
    if data.get("meetings") is None:
        canvas.unavailable(report.unavailable()["meetings_booked"])
        canvas.space(4)
        canvas.paragraph(
            "This report will not infer a meeting from the words in a reply. "
            "\"Let's chat\", \"send me a calendar\" and \"next week works\" "
            "are intentions, and counting them as meetings is how a report "
            "reports something that did not happen.")
    else:
        canvas.metrics([("Meetings", _n(data.get("meetings")), "recorded")],
                       per_row=3)


def _observations(canvas, data):
    canvas.heading("Observations")
    canvas.note(
        "Generated by comparing counted values against stated thresholds. "
        "No model writes these.")
    canvas.space(6)
    for kind, text in observations(data):
        canvas.bullet(text, {"good": GOOD, "warn": WARN}.get(kind, BRAND))
        canvas.space(2)


def _verification(canvas, data):
    canvas.heading("Verification")
    verification = data.get("verification") or {}
    canvas.metrics([
        # "Confirmed", not "two providers". The count is confirmations
        # obtained, not providers asked - two providers both answering
        # `unknown` is not a verified address, and the tile used to say it
        # was.
        ("Double verified", _n(verification.get("double")),
         "enough independent confirmations"),
        ("Held for a second", _n(verification.get("single")),
         "one confirmation so far"),
        ("Disagreements", _n(verification.get("disagreement")), "held"),
        ("Invalid", _n(verification.get("invalid")), "not used"),
        ("Addresses", _n(verification.get("addresses")),
         "the denominator for all four"),
    ])
    canvas.space(4)
    canvas.paragraph(
        "No address is used on the strength of a single provider. Where two "
        "disagreed, the contact is held for a person rather than sent to on a "
        "guess.")


def _security(canvas, data):
    canvas.heading("Email Security and MX")
    mx = data.get("mx") or {}
    rows = [(str(k), _n(v)) for k, v in sorted(mx.items(),
                                               key=lambda kv: -(kv[1] or 0))]
    canvas.table(["Gateway", "Contacts"], rows,
                 [WIDTH * 0.68, WIDTH * 0.32], ["l", "r"],
                 note="Screening runs before any verifier credit is spent. A "
                      "blocked gateway moves a contact to LinkedIn-only; it "
                      "is not a delivery failure.")
    canvas.space(6)
    canvas.metrics([
        ("MX blocked", _n(data.get("contacts_mx_blocked")), "email ruled out"),
        ("LinkedIn only", _n(data.get("contacts_linkedin_only")), "reachable"),
    ], per_row=3)


def _providers(canvas, data):
    canvas.heading("Provider Usage")
    rows = []
    for name, usage in sorted((data.get("providers") or {}).items()):
        rows.append((name,
                     _n(usage.get("calls")),
                     _n(usage.get("successes")),
                     _n(usage.get("failures")),
                     usage.get("cost") if usage.get("cost") is not None
                     else "not reported"))
    canvas.table(["Provider", "Calls", "Successes", "Failures", "Known cost"],
                 rows,
                 [WIDTH * 0.32, WIDTH * 0.15, WIDTH * 0.17, WIDTH * 0.16,
                  WIDTH * 0.20],
                 ["l", "r", "r", "r", "r"],
                 note="Cost is reported only where a provider reports it. An "
                      "estimate is never printed as spend.")


def _operations(canvas, data):
    canvas.heading("Operations")
    ops = data.get("operations") or {}
    canvas.metrics([
        ("Jobs", _n(ops.get("jobs")), "all states"),
        ("Failed jobs", _n(ops.get("failed_jobs")), "need attention"),
        # Records, not contacts. `_operations_counts` counts records
        # whose state is `held`; the label said contacts, which is a
        # different and larger number.
        ("Held companies", _n(ops.get("held")), "record state is held"),
        ("Unmatched replies", _n(ops.get("unmatched")), "need a person"),
    ])
    canvas.space(4)
    canvas.subheading("Notifications")
    notifications = ops.get("notifications") or {}
    rows = [(str(k).title(), _n(v)) for k, v in sorted(notifications.items())]
    canvas.table(["Status", "Notifications"], rows,
                 [WIDTH * 0.68, WIDTH * 0.32], ["l", "r"],
                 note="Slack posting is disabled in this build. Notifications "
                      "are routed and recorded; none is posted.")


# Which "cannot be measured" entries a client-facing document may carry.
#
# The same allowlist `src/web/pages.py` applies to the client dashboard, and
# for the same reason: the two entries deliberately missing from it explain
# themselves by naming a supplier. `actual_credits_per_record` says
# "ContactOut reports usage per account", and `decision_makers_found` talks
# about enrichment runs. A report appendix is not where a client learns the
# vendor stack, and an appendix is exactly the page nobody re-reads before
# sending.
CLIENT_SAFE_UNAVAILABLE = ("meetings_booked", "opens",
                           "email_and_linkedin_eligibility")


def _appendix(canvas, data, template=EXECUTIVE):
    canvas.heading("Appendix: What This Report Cannot Measure")
    canvas.paragraph(
        "Naming these is the point. A dashboard that shows zero for something "
        "nothing observes teaches people to read an absence as a result.")
    canvas.space(6)
    entries = report.unavailable()
    if template != INTERNAL:
        entries = {k: v for k, v in entries.items()
                   if k in CLIENT_SAFE_UNAVAILABLE}
    for key, why in sorted(entries.items()):
        canvas.subheading(key.replace("_", " ").capitalize())
        canvas.paragraph(why, 9, MUTED, indent=10)
        canvas.space(2)
    if template != INTERNAL:
        canvas.space(4)
        canvas.note(
            "Some limits of this system are operational rather than "
            "reportable, and are tracked internally by Resonate.")


# ------------------------------------------- the monthly report's sections
#
# Ten sections the executive report does not have. Each follows the same two
# rules as the rest of this module: every number comes from `src/report.py`,
# and anything nobody can know is named rather than shown as zero.
#
# The four narrative sections - takeaways, learned, next, and the summary's
# override - read from the draft rather than from the data. That is the whole
# point of `src/reportdraft.py`: the words are a person's, the numbers are
# counted, and there is nowhere for the two to mix.


def _narrative(meta, key):
    """One editable block, or None if nobody has written it."""
    return ((meta or {}).get("narrative") or {}).get(key) or None


def _lines(text):
    return [line.strip() for line in str(text or "").split("\n")
            if line.strip()]


def _takeaways(canvas, data, meta=None):
    canvas.heading("Key Takeaways")
    written = _narrative(meta, "takeaways")
    if written:
        for line in _lines(written):
            canvas.bullet(line)
            canvas.space(2)
        return
    # Nobody has edited them, so show the deterministic ones with a note
    # saying so. A client should be able to tell a written takeaway from a
    # generated one.
    for kind, text in observations(data)[:5]:
        canvas.bullet(text, {"good": GOOD, "warn": WARN}.get(kind, BRAND))
        canvas.space(2)
    canvas.space(4)
    canvas.note("Generated from counted values against stated thresholds. "
                "Not yet edited.")


def _reachable(data):
    """How many people email can actually reach.

    `contacts_verified` counts addresses that survived double verification.
    This additionally requires email security to allow the domain, which is
    what every sentence in these reports says was applied. Falls back for
    data counted before the two were separated.
    """
    value = data.get("contacts_email_reachable")
    return data.get("contacts_verified") if value is None else value


def _email(canvas, data, meta=None):
    canvas.heading("Email Performance")
    sent = data.get("emails_pushed")
    canvas.metrics([
        ("People contactable", _n(_reachable(data)),
         "verified and screened"),
        ("Emails confirmed sent", _n(sent), "touches"),
        ("Replies", _n(data.get("replies")), "all channels"),
        ("Positive replies", _n(data.get("positive_replies")), "reviewed"),
    ])
    canvas.space(4)
    canvas.table(
        ["Measure", "Value", "Rate"],
        [("Emails confirmed sent", _n(sent),
          _rate(sent, _reachable(data))),
         ("Replies", _n(data.get("replies")),
          _rate(data.get("replies"), sent)),
         ("Positive replies", _n(data.get("positive_replies")),
          _rate(data.get("positive_replies"), sent)),
         ("Delivered", _n(data.get("emails_delivered")),
          _rate(data.get("emails_delivered"), sent))],
        [WIDTH * 0.46, WIDTH * 0.22, WIDTH * 0.32], ["l", "r", "r"],
        note="Delivery is reported only where the sending platform reports "
             "it. With nothing sent this reads n/a, because 0 delivered of "
             "nothing is not a fact about deliverability. With something "
             "sent and nothing confirmed it reads 0, which is a real "
             "number and worth asking about.")


def _linkedin(canvas, data, meta=None):
    canvas.heading("LinkedIn Performance")
    linkedin = data.get("linkedin") or {}
    if not linkedin:
        canvas.unavailable(
            "No LinkedIn activity has been confirmed in this period. "
            "Connection acceptance is never inferred: if the provider has not "
            "reported an acceptance, this report does not count one.")
        return
    canvas.metrics([
        ("Connection requests", _n(linkedin.get("requests")), "sent"),
        ("Accepted", _n(linkedin.get("accepted")), "reported"),
        ("Messages", _n(linkedin.get("messages")), "confirmed sent"),
        ("Replies", _n(linkedin.get("replies")), ""),
    ])
    canvas.space(4)
    canvas.table(
        ["Measure", "Value", "Rate"],
        [("Acceptance", _n(linkedin.get("accepted")),
          _rate(linkedin.get("accepted"), linkedin.get("requests"))),
         ("Reply rate", _n(linkedin.get("replies")),
          _rate(linkedin.get("replies"), linkedin.get("messages")))],
        [WIDTH * 0.46, WIDTH * 0.22, WIDTH * 0.32], ["l", "r", "r"],
        note="Acceptance is counted from provider-reported events only.")


def _pipeline(canvas, data, meta=None):
    canvas.heading("Pipeline")
    rows = data.get("pipeline") or []
    if not rows:
        canvas.unavailable(
            "No positive replies in this period, so there is nothing in the "
            "pipeline yet.")
        return
    canvas.paragraph(
        "Everyone who replied positively, and where each conversation stands. "
        "Reply text is not reproduced here.")
    canvas.space(6)
    canvas.table(
        ["Contact", "Company", "Role", "Channel", "Sender", "Status"],
        [(r.get("contact"), r.get("company"), r.get("title"),
          r.get("channel"), r.get("sender"), r.get("status"))
         for r in rows],
        [WIDTH * 0.19, WIDTH * 0.21, WIDTH * 0.17, WIDTH * 0.13,
         WIDTH * 0.15, WIDTH * 0.15],
        ["l", "l", "l", "l", "l", "l"])


def _accounts(canvas, data, meta=None):
    canvas.heading("Account Engagement")
    accounts = data.get("accounts") or {}
    if not accounts:
        # Every other section that reads an unassembled key says so.
        # This one printed six `n/a` tiles in a client-facing document,
        # which reads as "we measured and found nothing".
        canvas.unavailable(
            "Account-level engagement is not assembled for this report. "
            "The per-account view is on the account screens; this section "
            "has no data behind it rather than nothing to report.")
        return
    canvas.paragraph(
        "Outreach is account-based: one company may have several decision "
        "makers approached by several people. These count companies, not "
        "contacts.")
    canvas.space(6)
    # THE OPERATOR'S EIGHT STATES, in the operator's order, one tile each.
    # Every account sits in exactly one of them, so the eight sum to the
    # estate - which is why `in_flight` is NOT a tile here. It is a sum of
    # four of them and printing it alongside would invite adding it in.
    canvas.metrics([
        ("Untouched", _n(accounts.get("untouched")), "nothing sent yet"),
        ("Sequenced", _n(accounts.get("sequenced")), "in a live sequence"),
        ("Engaged", _n(accounts.get("engaged")),
         "a touch landed, no reply yet"),
        ("Replied", _n(accounts.get("replied")), "somebody wrote back"),
    ])
    canvas.metrics([
        ("Meetings", _n(accounts.get("meeting")), "a meeting happened"),
        ("Won", _n(accounts.get("won")), ""),
        ("Lost", _n(accounts.get("lost")), ""),
        ("Do not contact", _n(accounts.get("do_not_contact")),
         "asked to be left alone"),
    ])
    canvas.space(4)
    # UNANSWERABLE GETS ITS OWN TILE AND ITS OWN SENTENCE. It is not a
    # state and it is never folded into `untouched` - that fold is the one
    # specific falsehood this section was rebuilt to stop, because "1,530
    # untouched" and "we cannot currently tell you" are different claims
    # and only one of them is true. A tile that appeared only when the
    # number was non-zero would be a tile nobody notices has appeared, so
    # it renders at zero too.
    canvas.metrics([
        ("Cannot be placed", _n(accounts.get("unanswerable")),
         "see the note below"),
        ("Multi-contact accounts", _n(accounts.get("multi_dm")),
         "more than one decision maker worked"),
        ("Referrals", _n(accounts.get("referrals")),
         "one contact pointing to another"),
    ], per_row=3)
    if accounts.get("unanswerable"):
        canvas.note(
            "%d account(s) could not be placed in a state: our own record of "
            "what was sent is not recording this client's sends yet, so we "
            "will not assert that nobody has been contacted. This is NOT a "
            "count of untouched accounts and must not be read as one."
            % accounts["unanswerable"])
    # WHY TWO OF THE EIGHT ARE ZERO, said out loud. Nothing in this system
    # records a deal; the meetings ledger is hand-fed and stops at the
    # meeting. A client reading "0 won" as a measurement rather than as an
    # absence of any source for the number is the failure this prevents.
    without = [str(s) for s in (data.get("accounts_without_a_source") or [])]
    if without:
        canvas.note(
            "%s: this system has no source for %s. The figure above is the "
            "absence of a record, not a measurement of the outcome - deals "
            "are tracked outside this report."
            % (" and ".join(w.replace("_", " ").title() for w in without),
               "them" if len(without) > 1 else "it"))


def _geography(canvas, data, meta=None):
    canvas.heading("Geography")
    if data.get("by_country"):
        _breakdown_table(canvas, "Country", data["by_country"])
    if data.get("by_region"):
        canvas.space(4)
        _breakdown_table(canvas, "Region", data["by_region"])
    if not data.get("by_country") and not data.get("by_region"):
        canvas.unavailable(
            "No geography has been recorded for these companies yet. It "
            "populates once qualification stores location evidence.")


def _senders(canvas, data, meta=None):
    canvas.heading("Sender Performance")
    rows = data.get("by_sender") or []
    if not rows:
        canvas.unavailable(
            "No confirmed touch carries a sender yet, so there is nothing to "
            "attribute.")
        return
    canvas.paragraph(
        "A human identity, not an inbox. One person may send from several "
        "inboxes; the prospect sees the person.")
    canvas.space(6)
    canvas.table(
        ["Sender", "Channel", "Touches", "Replies", "Positive", "Reply rate"],
        [(r.get("sender"), r.get("channel"), _n(r.get("touches")),
          _n(r.get("replies")), _n(r.get("positive")),
          _rate(r.get("replies"), r.get("touches")))
         for r in rows],
        [WIDTH * 0.26, WIDTH * 0.15, WIDTH * 0.13, WIDTH * 0.13,
         WIDTH * 0.13, WIDTH * 0.20],
        ["l", "l", "r", "r", "r", "r"],
        note="No ranking. A sender with nine touches and one reply is not "
             "outperforming one with four hundred; sample sizes are shown so "
             "nobody reads it that way.")


def _trend(canvas, data, meta=None):
    canvas.heading("Month over Month")
    months = data.get("months") or []
    if len(months) < 2:
        canvas.unavailable(
            "Month-over-month needs at least two periods of recorded "
            "activity. There is one.")
        return
    canvas.table(
        ["Month", "Contacted", "Touches", "Replies", "Positive",
         "Reply rate"],
        [(m.get("month"), _n(m.get("contacted")), _n(m.get("touches")),
          _n(m.get("replies")), _n(m.get("positive")),
          _rate(m.get("replies"), m.get("touches")))
         for m in months],
        [WIDTH * 0.20, WIDTH * 0.16, WIDTH * 0.16, WIDTH * 0.16,
         WIDTH * 0.16, WIDTH * 0.16],
        ["l", "r", "r", "r", "r", "r"])
    canvas.space(8)
    canvas.bars([(m.get("month"), m.get("positive") or 0) for m in months])


def _learned(canvas, data, meta=None):
    canvas.heading("What We Learned")
    written = _narrative(meta, "learned")
    if written:
        for line in _lines(written):
            canvas.bullet(line)
            canvas.space(2)
    else:
        for kind, text in observations(data):
            canvas.bullet(text, {"good": GOOD, "warn": WARN}.get(kind, BRAND))
            canvas.space(2)
    canvas.space(6)
    canvas.note("Every comparison here carries its sample size. A difference "
                "between two small groups is a difference between two small "
                "groups, not a finding.")

    worked = _narrative(meta, "what_worked")
    changed = _narrative(meta, "what_changed")
    if worked:
        canvas.subheading("What worked")
        canvas.paragraph(worked)
    if changed:
        canvas.subheading("What changed")
        canvas.paragraph(changed)


def _next(canvas, data, meta=None):
    canvas.heading("Next Month")
    written = _narrative(meta, "next_steps")
    if written:
        canvas.paragraph(written)
        canvas.space(6)
    groups = {}
    for entry in (meta or {}).get("recommendations") or []:
        groups.setdefault(entry.get("kind"), []).append(entry.get("text"))
    if not groups and not written:
        canvas.unavailable(
            "No recommendations have been written for this period yet. They "
            "are authored by a person before the report is sent.")
        return
    for kind in ("scale", "test", "stop", "follow_up"):
        entries = groups.get(kind) or []
        if not entries:
            continue
        canvas.subheading(kind.replace("_", " ").title())
        for text in entries:
            canvas.bullet(text)
            canvas.space(2)
        canvas.space(4)


# Every entry takes (canvas, data, meta). A renderer that ignores `meta`
# still accepts it: a dispatch table whose entries have different signatures
# is a dispatch table with a branch in it, and that branch is what hid the
# template from the appendix.
RENDERERS = {
    "takeaways": _takeaways,
    "email": _email,
    "linkedin": _linkedin,
    "pipeline": _pipeline,
    "accounts": _accounts,
    "geography": _geography,
    "senders": _senders,
    "trend": _trend,
    "learned": _learned,
    "next": _next,
    "summary": _summary,
    "funnel": lambda c, d, m=None: _funnel(c, d),
    "campaigns": lambda c, d, m=None: _campaigns(c, d),
    "channels": lambda c, d, m=None: _channels(c, d),
    "personas": lambda c, d, m=None: _personas(c, d),
    "angles": lambda c, d, m=None: _angles(c, d),
    "audience": lambda c, d, m=None: _audience(c, d),
    "replies": lambda c, d, m=None: _replies(c, d),
    "positive": lambda c, d, m=None: _positive(c, d),
    "meetings": lambda c, d, m=None: _meetings(c, d),
    "observations": lambda c, d, m=None: _observations(c, d),
    "verification": lambda c, d, m=None: _verification(c, d),
    "security": lambda c, d, m=None: _security(c, d),
    "providers": lambda c, d, m=None: _providers(c, d),
    "operations": lambda c, d, m=None: _operations(c, d),
    "appendix": lambda c, d, m=None: _appendix(
        c, d, (m or {}).get("template", EXECUTIVE)),
}


# -------------------------------------------------------------------- build

def build(data, meta, sections=None):
    """The whole document, as PDF bytes.

    `data` is whatever `src/web/api.py` assembled from `src/report.py`. This
    function counts nothing; it lays out what it is given, and a key it does
    not find renders as "not tracked" rather than as zero.
    """
    template = meta.get("template") or EXECUTIVE
    if template not in TEMPLATES:
        raise ValueError(f"unknown report template: {template!r}")
    chosen = resolve_sections(template, sections)

    meta = dict(meta)
    meta.setdefault("template_label", TEMPLATE_LABEL[template])
    meta.setdefault("title", TEMPLATE_LABEL[template])
    meta.setdefault("generated_at", store.now()[:10])
    meta.setdefault("generated_by", "unknown")
    meta.setdefault("report_id", "-")
    meta.setdefault("campaign_label", "All campaigns")
    meta.setdefault("workspace_slug", "-")
    meta.setdefault("period", "All time")

    document = pdf.Document(
        title=f"{meta['workspace_name']} - {meta['template_label']}",
        subject=f"Reporting period: {meta['period']}")
    canvas = Canvas(document, meta)
    _cover(canvas, meta)

    for key in chosen:
        canvas.new_page()
        # Every renderer takes `meta`; the ones that ignore it accept it as a
        # keyword default. Branching on the section key here was how the
        # appendix ended up unable to see which template it was rendering
        # for, and printed a supplier's name into a client's document.
        RENDERERS[key](canvas, data, meta)

    _footers(document, meta)
    return document.render()


def _footers(document, meta):
    """Page numbers last, because the count is not known until the end."""
    pages = document.pages
    total = len(pages)
    for index, page in enumerate(pages, start=1):
        if index == 1:
            continue                     # the cover carries its own footer
        page.line(LEFT, 58, RIGHT, 58, RULE, 0.6)
        page.text(LEFT, 44, f"Resonate Group - {meta['workspace_name']}",
                  pdf.HELV, 7.5, FAINT)
        page.text_right(RIGHT, 44, f"Page {index} of {total}", pdf.HELV, 7.5,
                        FAINT)


def filename(meta):
    """A filename somebody can find again in a folder of thirty of them."""
    slug = "".join(ch if ch.isalnum() else "-"
                   for ch in str(meta.get("workspace_slug") or "workspace"))
    period = str(meta.get("period") or "all-time").replace(" ", "-")
    period = "".join(ch for ch in period if ch.isalnum() or ch == "-")
    return f"resonate-{slug}-{meta.get('template', EXECUTIVE)}-{period}.pdf"


def today():
    return datetime.date.today().isoformat()
